name: krisbook
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.7.3
  firebase_auth: 0.5.20
  googleapis: ^0.52.0
  firebase_storage: 1.0.2
  shared_preferences: 0.4.2
  cached_network_image: ^0.4.1  # Getting picture from internet and storing in cache
  image_picker: 0.4.1
  intl: 0.15.7
  fluttertoast: ^2.0.7
  flutter_launcher_icons: "^0.6.1"
<<<<<<< HEAD
=======
  translator: ^0.1.0+4
>>>>>>> hanzhe

flutter_icons:
  android: true 
  ios: false
  image_path: "assets/AirVenue_Logo.png"
  adaptive_icon_background: "#FFFAFAFA"
  adaptive_icon_foreground: "assets/icon/icon-foreground.png"



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/talk.png
    - assets/logo.png
    - assets/mimi1.gif
    - assets/mimi2.gif
    - assets/mimi3.gif
    - assets/mimi4.gif
    - assets/mimi5.gif
    - assets/mimi6.gif
    - assets/mimi7.gif
    - assets/mimi8.gif
    - assets/mimi9.gif
    - assets/logo_announce.png
    - assets/AirVenue_Logo.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: lib/fonts/Raleway-Regular.ttf
        - asset: lib/fonts/Raleway-Italic.ttf
        - asset: lib/fonts/Raleway-Light.ttf
          style: italic
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
